### ISSUE TITLE
Not working with latest HA (0.43.0)

### ISSUE THREAD

**Issue by kennhardy** [drytoastman/haconfig#1]
I just tried to implement this with my HA 0.43.0. Had a lot of errors during implementation, but straightened out most of them. Right now i'm stuck at:
```
17-04-27 17:16:04 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform bwalarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 150, in _async_setup_platform
    entity_platform.async_schedule_add_entities, discovery_info
  File "/home/kennhard/.homeassistant/custom_components/alarm_control_panel/bwalarm.py", line 60, in async_setup_platform
    yield from async_add_devices([alarm])
TypeError: 'NoneType' object is not iterable

```
And:
```
  File "/home/kennhard/.homeassistant/custom_components/switch/bwio.py", line 3, in <module>
    import custom_components.bwio as bwio
  File "/home/kennhard/.homeassistant/custom_components/bwio.py", line 14, in <module>
    from homeassistant.components.binary_sensor import BinarySensorDevice, SENSOR_CLASSES
ImportError: cannot import name 'SENSOR_CLASSES'
```

After trying for to get past this error thinking i had done something wrong i found others commenting here: [https://community.home-assistant.io/t/a-different-take-on-an-alarm-system/7809/30](https://community.home-assistant.io/t/a-different-take-on-an-alarm-system/7809/30)

So hopefully I have not done something wrong, but theres is an issue somewhere after upgrading to 0.43.0.
